name: "Sphinx: Render docs"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install project & docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./src
          pip install sphinx sphinx_click

      - name: Build Sphinx docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs
          build-command: "sphinx-build -b html . _build/html --keep-going --no-color"

      - name: Upload HTML docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html